### ISSUE TITLE
Basic Tests

### ISSUE THREAD

**Issue by vking45** [kamuikatsurgi/NoRug#3]
There are no tests in the current codebase, some solid written tests need to be added. 

The tests can be very basic, here are some of the ideas - 
- attempt to participate in the token sale with an asset that is not being accepted
- try to participate in the token sale after the sale has ended

More advanced tests will be added as we move towards our target implementation.

**Comment by kamuikatsurgi** [comment]
Implemented in 98b2c61, closing this!
